### ISSUE TITLE
Main hours widget block

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-wp-plugins#38]
https://xd.adobe.com/view/7050af49-1ef8-4e98-a422-e2a55b8a60ba-2503/screen/12bc8dd0-4bd9-4748-8ee2-f31e314d9326/

**Comment by wrenaria** [comment]
The "Show hours for Shields services" button is getting lost / easy to miss. Needs at least **1-1.5rem** of space between it and the hours above it and **bold** the text. That should help. 

Also add the word "library" so it says `Show hours for Shields Library services`

Otherwise, looks and functions as expected!
