### ISSUE TITLE
Single Location QA

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-wp-plugins#63]
I mocked up a single location page:

https://sandbox.library.ucdavis.edu/location/peter-j-shields-library/

@wrenaria You can put all your requests in this one issue, and ill route them to the right subissue/person.

**Comment by wrenaria** [comment]
@spelkey-ucd This is looking really good! Some text styles were incorrect (wrong h style and h level), but I fixed them myself with fancy headings because it's just WYSIYG editing. 

I do have a couple issues of concern that would affect the core blocks (and they are things I've been thinking about for other pages as well), and a couple that are location page specific.

## Issue 1: Heading Styles on Marketing Horizontal Blocks
I think this one will technically break us from the SiteFarm mold, but I'd like to have the Marking Highlights support the h5 styling for the title (looks like they currently use h4) because when we use them in 3 columns like this, they look bad at smaller sizes (and we do this on several pages -- it's the way we use them most).

Current h4 styling on Small Screen | With h5 Styling
--- | ---
![Screen Shot 2022-07-06 at 2 28 23 PM](https://user-images.githubusercontent.com/17831969/177646818-7517972c-a226-4649-884f-802188fc251a.png) | ![Screen Shot 2022-07-06 at 2 28 48 PM](https://user-images.githubusercontent.com/17831969/177646812-a4873aa7-4454-483a-b2f7-1a536b6603ae.png)

While we _could_ move to just 2 column layouts, that increases the page length significantly and how quickly scannable the content can be. The 3 columns, I think, makes for better desktop UX if we can resolve the text issue.

## Issue 2: Separator Margin
In general, I think the 2rem margin looks good in _most_ cases, but on pages like this, the content gets pushed too far away from each other and loses contextual cohesion. Can we default to 2rem for separator but add an option for 1rem margin for things that need to live closer together?

In particular, I'm referring to this piece of the page:
| Current (2rem) | Goal (1 rem) |
|--- | ---|
| ![Screen Shot 2022-07-06 at 2 26 26 PM](https://user-images.githubusercontent.com/17831969/177646406-699658d6-980d-44ec-9914-7d9261da2d61.png) | ![Screen Shot 2022-07-06 at 2 26 57 PM](https://user-images.githubusercontent.com/17831969/177646412-534c3957-f0cb-4050-9844-b13e34a86f56.png)

## Issue 3: Icons on Contact Information Block
I know my mockup has the generic website icons for directory and services, but I am wondering if we can enable custom icon selection there or maybe just add a "Directory" option?

It would be nice to use **address-book** icon for service and staff directory links, for example. Otherwise, I think the way this is implemented is fine.

## Issue 4: Archives and Special Collections / Hours Block Questions
While ASC will be highlighted on the Locations page, they will **not** have a dedicated "location page" to construct, we will be linking to the [existing ASC homepage](https://stage.library.ucdavis.edu/archives-and-special-collections/). Just want to make sure that's known/not a problem. The [Map Collection](https://stage.library.ucdavis.edu/archives-and-special-collections/our-collections/map-collection/) will also **not** have a location page, but it will probably make use of the hours widget. 

As for their Hours display, ASC will want the Map Collection shown along with their primary hours. Is this currently possible? Looking at the hours widget, I see an option for "show only selected children" and location post ids, but it is not clear where to find this information or if this is where I would control that (aka this is not user friendly, I have no idea what to do with this field).

![Screen Shot 2022-07-06 at 2 54 13 PM](https://user-images.githubusercontent.com/17831969/177650033-f3c08710-dbea-4400-be89-b81139e350ad.png)

That's all for now!

**Comment by wrenaria** [comment]
@spelkey-ucd Issue 1 -- Global replace for the headings. I think I prefer consistency across the board for these blocks.

Otherwise, this all sounds fine. Thanks!
